#!/usr/bin/env bash
IMAGE=maven:alpine
WORK=/src

OPTS=

if [ ! -z ${HG2C_NETWORK+x} ]; then
    OPTS="$OPTS --network ${HG2C_NETWORK}"
fi

if [ ! -z ${HG2C_M2+x} ]; then
    OPTS="$OPTS -v ${HG2C_M2}:/root/.m2"
else
    OPTS="$OPTS -v ${HOME}/.m2:/root/.m2"
fi

docker run --rm -ti \
       $OPTS \
       -w $WORK \
       -v `pwd -P`:$WORK $IMAGE bash

# /usr/share/maven# cat conf/settings.xml
