#!/usr/bin/env bash
PROXY_HUB=${PROXY_HUB-hub.huwo.io/vendor}

docker-pull() {
    ORIGIN_IMAGE=$1

    PROXY_IMAGE=${ORIGIN_IMAGE}
    PROXY_IMAGE=${ORIGIN_IMAGE//\//.}
    PROXY_IMAGE=${PROXY_HUB}/${PROXY_IMAGE}

    run docker push $PROXY_IMAGE
    run docker tag $PROXY_IMAGE $ORIGIN_IMAGE

    # run docker rmi $PROXY_IMAGE
    echo "[INFO] ${ORIGIN_IMAGE} <= ${PROXY_IMAGE}."
    echo
}

docker-pull "$1"
