#!/usr/bin/env bash
DOCKER_IMAGES_LIST=$1

docker-push() {
    ORIGIN_IMAGE_NAME=$1
    NEW_IMAGE_NAME=hub.huwo.io/vendor/${ORIGIN_IMAGE_NAME//\//-}
    docker tag $ORIGIN_IMAGE_NAME $NEW_IMAGE_NAME
    docker push $NEW_IMAGE_NAME
}

while IFS= read -r name
do
    docker-push "$name"
done < "$DOCKER_IMAGES_LIST"
