#!/usr/bin/env bash
MOVIE_RSYNC_OPTS="-rltDv --exclude=.DS_Store --exclude=@eaDir"
if [[ $DRY_RUN == true ]]; then
    MOVIE_RSYNC_OPTS+=" --dry-run"
fi

gopro-push() {
    echo-and-run rsync $MOVIE_RSYNC_OPTS \
        /Users/luotao/Movies/$1/ \
        thresh:/volume1/video/family/$1/
}

gopro-push xy
gopro-push GoPro
gopro-push FinalCut
