#!/usr/bin/env bash
MOVIE_RSYNC_OPTS="-rltDv --exclude=.DS_Store --exclude=@eaDir"
if [[ $DRY_RUN == true ]]; then
    MOVIE_RSYNC_OPTS+=" --dry-run"
fi

gopro-pull() {
    echo-and-run rsync $MOVIE_RSYNC_OPTS \
        thresh:/volume1/video/family/$1/ \
        /Users/luotao/Movies/$1/
}

gopro-pull xy
gopro-pull GoPro
gopro-pull FinalCut
