#!/usr/bin/env bash
MOVIE_RSYNC_OPTS="-rltDv --exclude=.DS_Store --exclude=@eaDir"
# MOVIE_RSYNC_OPTS+=" --dry-run"

gopro-pull() {
    run rsync $MOVIE_RSYNC_OPTS \
        thresh:/volume1/video/family/$1/ \
        /Users/luotao/Movies/$1/
}

gopro-pull xy
gopro-pull GoPro
gopro-pull FinalCut
