#!/usr/bin/env bash
HOST=$1
# if [[ ${SCRIPT_ROOT} == $HOME* ]]; then
#     SCRIPT_ROOT=~${SCRIPT_ROOT#$HOME}
# fi

run ssh $HOST \"mkdir -p ${SCRIPT_ROOT}\"
run rsync -avzhe ssh --delete --progress ${SCRIPT_ROOT}/ $HOST:$WORKDIR/
