#!/usr/bin/env bash
ARG1=$1
ARG2=$2
ARG3=$3

echo "arg1: $ARG1"
echo "arg2: $ARG2"
echo "arg3: $ARG3"

echo kubectl create -f "https://raw.githubusercontent.com/\
jaegertracing/jaeger-kubernetes/master/all-in-one/\
jaeger-all-in-one-template.yml"
