#!/usr/bin/env bash
set -e

OPTS=
FILE=docker-compose.yml

while [ $# -gt 0 ]
do
    case "$1" in
        -f | --file ) FILE="$2"; shift 2;;
        * ) OPTS="$OPTS $1"; shift;;
    esac
done

docker-compose -f <(
    cat $FILE
    if [ ! -z ${HG2C_NETWORK+x} ]; then
        cat <<EOF
networks:
  default:
    external:
      name: ${HG2C_NETWORK}
EOF
    fi
) --project-directory $(pwd) $OPTS


# docker network create --driver=bridge --subnet=10.43.0.0/16 dc0
# export HG2C_NETWORK=dc0
