#!/usr/bin/env bash
set -e

OPTS=
FILE=docker-compose.yml

while [ $# -gt 0 ]
do
    case "$1" in
        -f | --file ) FILE="$2"; shift 2;;
        * ) OPTS="$OPTS $1"; shift;;
    esac
done

# TODO: if env set docker-bridge
docker-compose -f <(
cat $FILE
cat <<EOF
networks:
  default:
    external:
      name: dc0
EOF
) --project-directory $(pwd) $OPTS
